version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qeats-backend
    ports:
      - '8081:8081'
    environment:
      SPRING_REDIS_PORT: 6379
    networks:
      - qeats-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qeats-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      SPRING_BOOT_URL: http://backend:8081
      PORT: 3000
    networks:
      - qeats-net

networks:
  qeats-net:
    driver: bridge
